import { z } from 'zod';
import { TEMPLATE_KINDS, TEMPLATE_VARIABLES } from '../types/email';
import { objectIdSchema } from './common';

/**
 * An email address accepted from admin input.
 *
 * `email()` alone is not enough here, because these values are written into message headers.
 * A carriage return or line feed inside an address lets an attacker append headers of their
 * own — a `Bcc:` that silently copies every notification elsewhere, or a second `From:`.
 * Zod's own email check would already reject those, but the rule is stated explicitly so it
 * cannot be lost if the address format is ever relaxed.
 */
export const headerSafeEmail = z
  .string()
  .trim()
  .toLowerCase()
  .max(200)
  .email('Enter a valid email address')
  .refine((v) => !/[\r\n]/.test(v), 'An email address cannot contain line breaks');

/**
 * A header value that is not an address — a display name or a subject line.
 *
 * `min` is a parameter rather than something a caller chains on, because `.refine()` returns
 * an effect that no longer offers the string methods.
 */
export const headerSafeText = (max: number, min = 0, minMessage?: string) =>
  z
    .string()
    .trim()
    .min(min, minMessage)
    .max(max)
    .refine((v) => !/[\r\n]/.test(v), 'This field cannot contain line breaks');

/**
 * A comma-or-newline separated list of addresses, as an admin would type it.
 *
 * Accepting the messy form and normalising here means the admin UI can stay a single text
 * field while the stored value is always a clean array.
 */
export const emailListSchema = z
  .union([z.string(), z.array(z.string())])
  .transform((v) => (Array.isArray(v) ? v : v.split(/[,;\n]/)))
  .transform((list) => list.map((s) => s.trim().toLowerCase()).filter(Boolean))
  .pipe(z.array(headerSafeEmail).max(20, 'At most 20 addresses'));

export const emailSettingsSchema = z.object({
  notifyTo: headerSafeEmail,
  notifyCc: emailListSchema.default([]),
  notifyBcc: emailListSchema.default([]),
  senderName: headerSafeText(120, 1, 'Sender name is required'),
  replyTo: headerSafeEmail,
  sendClientConfirmation: z.boolean().default(true),
  sendAdminNotification: z.boolean().default(true),
});

export type EmailSettingsInput = z.infer<typeof emailSettingsSchema>;

/**
 * Rejects template syntax that asks for anything other than a known variable.
 *
 * Templates are data, not code: rendering only ever substitutes `{{name}}` for a value from
 * a fixed list. This check exists so an editor finds out at save time that `{{user.password}}`
 * or `{{#each}}` will not work, rather than shipping a template that silently renders the
 * placeholder as literal text to a client.
 */
const knownVariables = new Set<string>(TEMPLATE_VARIABLES);

export function unknownTemplateVariables(source: string): string[] {
  const found = new Set<string>();
  for (const match of source.matchAll(/\{\{\s*([^}]*?)\s*\}\}/g)) {
    const name = match[1] ?? '';
    if (!knownVariables.has(name)) found.add(name || '(empty)');
  }
  return [...found];
}

const templateBody = (max: number, label: string) =>
  z
    .string()
    .max(max)
    .superRefine((v, ctx) => {
      const unknown = unknownTemplateVariables(v);
      if (unknown.length > 0) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: `${label} uses unknown variables: ${unknown.join(', ')}. Allowed: ${TEMPLATE_VARIABLES.join(', ')}`,
        });
      }
    });

export const emailTemplateSchema = z.object({
  kind: z.enum(TEMPLATE_KINDS),
  name: headerSafeText(120, 2, 'Give the template a name'),
  description: z.string().trim().max(400).default(''),
  subject: templateBody(300, 'The subject').pipe(headerSafeText(300, 2, 'A subject is required')),
  html: templateBody(60_000, 'The HTML body').pipe(z.string().min(1, 'The HTML body cannot be empty')),
  text: templateBody(30_000, 'The plain-text body'),
  active: z.boolean().default(true),
});

export type EmailTemplateInput = z.infer<typeof emailTemplateSchema>;

/** Rendering a template against a lead, for the admin preview. */
export const templatePreviewSchema = z.object({
  subject: templateBody(300, 'The subject'),
  html: templateBody(60_000, 'The HTML body'),
  text: templateBody(30_000, 'The plain-text body').default(''),
  leadId: objectIdSchema.optional(),
});

/**
 * An admin reply.
 *
 * `dedupeKey` is generated by the browser when the composer opens and sent unchanged with
 * the submission, so a double-click or a retried request is recognised as the same reply
 * rather than sending the client two copies.
 */
export const adminReplySchema = z.object({
  subject: headerSafeText(300, 2, 'A subject is required'),
  html: z.string().min(1, 'Write a reply before sending').max(60_000),
  text: z.string().max(30_000).default(''),
  cc: emailListSchema.default([]),
  bcc: emailListSchema.default([]),
  templateId: objectIdSchema.optional(),
  dedupeKey: z.string().trim().min(8).max(64).regex(/^[A-Za-z0-9_-]+$/, 'Invalid key'),
});

export type AdminReplyInput = z.infer<typeof adminReplySchema>;

/**
 * A normalised inbound email.
 *
 * Providers disagree on shape, so each webhook adapter converts its payload into this before
 * anything downstream sees it. Fields are optional because a real inbound message often
 * lacks threading headers entirely.
 */
export const inboundEmailSchema = z.object({
  from: z.string().trim().max(320),
  to: z.string().trim().max(320).default(''),
  subject: z.string().max(500).default(''),
  text: z.string().max(200_000).default(''),
  html: z.string().max(500_000).default(''),
  messageId: z.string().trim().max(400).default(''),
  inReplyTo: z.string().trim().max(400).default(''),
  references: z
    .union([z.string(), z.array(z.string())])
    .default([])
    .transform((v) => (Array.isArray(v) ? v : v.split(/\s+/)))
    .transform((list) => list.map((s) => s.trim()).filter(Boolean).slice(0, 50)),
});

export type InboundEmailInput = z.infer<typeof inboundEmailSchema>;

export const unmatchedResolveSchema = z.object({
  leadId: objectIdSchema,
});

/**
 * An address that may be left blank.
 *
 * The site-settings screen allows an empty notification recipient, because the application
 * falls back to the public contact address. An empty string must therefore pass, while a
 * value that is present still has to be a real, header-safe address.
 */
export const optionalEmail = z
  .string()
  .trim()
  .toLowerCase()
  .max(200)
  .refine((v) => v === '' || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v), 'Enter a valid email address')
  .refine((v) => !/[\r\n]/.test(v), 'An email address cannot contain line breaks')
  .default('');
