import { NextResponse, type NextRequest } from 'next/server';
import { buildForwardHeaders, forwardJson, toNextResponse, unavailable, upstreamUrl } from '@/lib/api/adminProxy';

/**
 * Media upload.
 *
 * Uploads get their own route because forwarding the raw multipart bytes does not survive
 * the hop — the body arrives truncated and the API's parser reports "Unexpected end of
 * form". Instead the form is parsed here and a fresh `FormData` is sent upstream, so the
 * boundary and length are generated by the same client that writes the body.
 *
 * This is transport only. The API still authenticates the session, checks CSRF, sniffs the
 * file's actual bytes and enforces the size cap — none of which is duplicated here, so
 * there is no second set of rules to drift out of step.
 */

// Uploads are capped at 10 MB by the API; this route only needs to not reject them first.
export const maxDuration = 60;

export async function GET(request: NextRequest) {
  return forwardJson(request, ['media']);
}

export async function POST(request: NextRequest) {
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return NextResponse.json(
      { success: false, error: { code: 'MALFORMED_UPLOAD', message: 'That upload could not be read.' } },
      { status: 400 },
    );
  }

  const file = form.get('file');
  if (!(file instanceof File)) {
    return NextResponse.json(
      { success: false, error: { code: 'NO_FILE', message: 'No file was uploaded.' } },
      { status: 400 },
    );
  }

  // Rebuilt rather than reused, so the outgoing request carries a boundary matching the
  // bytes it actually sends.
  const outgoing = new FormData();
  outgoing.append('file', file, file.name);

  const alt = form.get('alt');
  if (typeof alt === 'string') outgoing.append('alt', alt);

  try {
    const upstream = await fetch(upstreamUrl(['media']), {
      method: 'POST',
      headers: buildForwardHeaders(request),
      body: outgoing,
      redirect: 'manual',
      cache: 'no-store',
      signal: AbortSignal.timeout(60_000),
    });
    return toNextResponse(upstream);
  } catch {
    return unavailable();
  }
}
